#!/usr/bin/env node
/**
 * Seed a THROWAWAY vault for driving the finance and meals surfaces by hand.
 *
 *   node scripts/seed-vault.mjs                 # scenario vault, prints the path
 *   node scripts/seed-vault.mjs --empty         # day-one vault: dirs only, no records
 *   node scripts/seed-vault.mjs --out <dir>     # somewhere specific
 *
 * Then:
 *
 *   DESVU_VAULT="$(node scripts/seed-vault.mjs)" npm run dev
 *
 * ---------------------------------------------------------------------------
 * IT WILL NOT WRITE TO THE REAL VAULT.
 * ---------------------------------------------------------------------------
 * `~/Documents/Dès vu` (and the iCloud path it symlinks to) holds the only copy of six
 * months of personal journal entries and has no git remote. This script refuses to write
 * anywhere under either path, and defaults to a fresh directory in `os.tmpdir()`.
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { mkdtempSync } from 'node:fs'
import { homedir, tmpdir } from 'node:os'
import path from 'node:path'

const argv = process.argv.slice(2)
const empty = argv.includes('--empty')
const outIndex = argv.indexOf('--out')
const requested = outIndex !== -1 ? argv[outIndex + 1] : null

// --- the guard ------------------------------------------------------------

const FORBIDDEN = [
  path.join(homedir(), 'Documents', 'Dès vu'),
  path.join(
    homedir(),
    'Library',
    'Mobile Documents',
    'iCloud~md~obsidian',
    'Documents',
    'Dès vu'
  ),
]

function refuseIfReal(target) {
  const resolved = path.resolve(target).normalize('NFC')
  for (const forbidden of FORBIDDEN) {
    const guard = path.resolve(forbidden).normalize('NFC')
    if (resolved === guard || resolved.startsWith(`${guard}${path.sep}`)) {
      console.error(`refusing to seed test data into the real vault: ${target}`)
      process.exit(1)
    }
  }
}

const root = requested
  ? (refuseIfReal(requested), path.resolve(requested))
  : mkdtempSync(path.join(tmpdir(), 'desvu-seed-'))

for (const dir of ['data', 'Inbox', 'Journal', 'Library', 'Brain Dump', 'Synthesis', 'Attachments']) {
  mkdirSync(path.join(root, dir), { recursive: true })
}

const write = (rel, value) =>
  writeFileSync(path.join(root, rel), `${JSON.stringify(value, null, 2)}\n`, 'utf8')

// A marker file, so `@shared/vault`'s strict discovery check recognises this directory as
// a vault. `DESVU_VAULT` is trusted without one, but a seeded vault that is only
// vault-SHAPED (a bare `data/` directory) is exactly the thing that once shadowed the
// real corpus — leaving the marker here means this directory is never ambiguous.
writeFileSync(
  path.join(root, 'data', 'SCHEMAS.md'),
  '# SCHEMAS (seeded throwaway vault)\n\nGenerated by `scripts/seed-vault.mjs`. Not the real corpus.\n',
  'utf8'
)

// --- dates ----------------------------------------------------------------

const pad = (n) => String(n).padStart(2, '0')
const toDate = (d) => `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`
const dayOffset = (delta) => {
  const d = new Date()
  d.setDate(d.getDate() + delta)
  return toDate(d)
}
const today = toDate(new Date())

let seq = 0
const id = (prefix) => `${prefix}-${String(++seq).padStart(3, '0')}`
const ts = (delta) => Date.now() - delta * 86_400_000

// --- day one --------------------------------------------------------------

if (empty) {
  // Nothing at all. `settings.json` is seeded by settingsRepository on first read, with
  // categories: [] and nutrition targets null — which is exactly what day one is.
  console.log(root)
  process.exit(0)
}

// --- settings -------------------------------------------------------------
// Categories exist here ONLY because they were "added in the app". They are not a
// default: `DEFAULT_SETTINGS.finance.categories` is `[]` and nothing in the renderer
// ever supplies a fallback list.

write('data/settings.json', {
  finance: {
    categories: [
      { name: 'groceries', limit: 250 },
      { name: 'coffee', limit: 60 },
      { name: 'transit', limit: 40 },
      { name: 'books', limit: null },
    ],
    currency: 'USD',
    month_starts_on: 1,
  },
  nutrition: { calorie_target: null, protein_target_g: null, show_targets: false },
  todos: { default_priority: 2, default_estimate_minutes: 30 },
  library: { auto_archive_days: 30 },
  synthesis: { journal_access: 'full' },
})

// --- finance --------------------------------------------------------------

/**
 * Spread `count` dates across the current month up to today — never into the future,
 * because a purchase dated next week is not a state the app should be demoed in.
 */
const monthDays = Number(today.slice(8, 10))
const inThisMonth = (index, count) =>
  `${today.slice(0, 7)}-${pad(Math.max(1, Math.round(((index + 1) / count) * monthDays)))}`

write('data/finance.json', {
  purchases: [
    // groceries goes OVER its 250 limit — the gold-not-red case.
    { i: 0, amount: 96.4, category: 'groceries', description: 'Giant Eagle, big shop' },
    { i: 1, amount: 118.2, category: 'groceries', description: 'Trader Joe’s' },
    { i: 2, amount: 97.4, category: 'groceries', description: 'Giant Eagle' },
    // coffee and transit stay under.
    { i: 3, amount: 18, category: 'coffee', description: 'Commonplace' },
    { i: 4, amount: 23, category: 'coffee', description: 'De Fer, twice' },
    { i: 5, amount: 22, category: 'transit', description: 'bus pass top-up' },
    // tracked but uncapped.
    { i: 6, amount: 19, category: 'books', description: 'DDIA, used' },
    // a category settings has never heard of — logs fine, off-budget line.
    { i: 7, amount: 28, category: 'vinyl', description: 'record shop, Bloomfield' },
    // no category at all — the uncategorised line.
    { i: 8, amount: 41, category: '', description: 'lunch, Tepper' },
    { i: 9, amount: 26, category: '', description: 'the thing I forgot to sort' },
    // income is a negative amount.
    { i: 10, amount: -820, category: 'income', description: 'TA stipend' },
  ]
    .map(({ i, ...rest }) => ({ date: inThisMonth(i, 11), ...rest }))
    // last month, so the month stepper has somewhere to go.
    .concat([
      { date: dayOffset(-40), amount: 74.5, category: 'groceries', description: 'last month' },
      { date: dayOffset(-38), amount: 12, category: 'coffee', description: 'last month, coffee' },
    ])
    .map((purchase, index) => ({
      id: id('p'),
      source: 'app',
      created_at: ts(index),
      ...purchase,
    })),
})

// --- meals ----------------------------------------------------------------

const MEALS = [
  // Today: two estimated (italic Cormorant), one measured, one with no numbers at all.
  { date: today, meal: 'breakfast', description: 'Oatmeal, banana', calories: 340, protein_g: 12, estimated: true },
  { date: today, meal: 'lunch', description: 'Chipotle bowl', calories: 780, protein_g: 42, estimated: true },
  { date: today, meal: 'snack', description: 'coffee and whatever was in the kitchen', calories: null, protein_g: null, estimated: false },
  { date: today, meal: 'dinner', description: 'Chicken, rice, broccoli', calories: 620, protein_g: 48, estimated: false },
]

for (let back = 1; back <= 12; back += 1) {
  const date = dayOffset(-back)
  // Days 4 and 9 back are deliberately blank — a real log has gaps, and the trend must
  // draw them as gaps rather than as zeros.
  if (back === 4 || back === 9) continue
  const wobble = ((back * 37) % 9) - 4
  MEALS.push(
    { date, meal: 'breakfast', description: 'eggs, toast', calories: 420 + wobble * 10, protein_g: 22, estimated: back % 3 === 0 },
    { date, meal: 'lunch', description: back % 2 ? 'burrito' : 'salad, chicken', calories: 700 + wobble * 20, protein_g: 40 + wobble, estimated: back % 3 === 0 },
    ...(back % 4 === 0
      ? // some days simply have no numbers, which is a complete entry
        [{ date, meal: 'dinner', description: 'dinner out with the lab', calories: null, protein_g: null, estimated: false }]
      : [{ date, meal: 'dinner', description: 'pasta', calories: 800 + wobble * 15, protein_g: 30, estimated: back % 3 === 0 }])
  )
}

write(
  'data/meals.json',
  MEALS.map((entry, index) => ({ id: id('m'), source: 'app', created_at: ts(index / 24), ...entry }))
)

// --- workouts -------------------------------------------------------------

const WORKOUTS = [
  { date: today, type: 'lift', description: 'Push day — bench 3x8 @155, ohp, dips', duration_minutes: 55 },
  { date: dayOffset(-1), type: 'run', description: 'Easy 3mi', duration_minutes: 28 },
  { date: dayOffset(-2), type: 'climb', description: 'Bouldering, felt strong', duration_minutes: null },
  { date: dayOffset(-3), type: 'lift', description: 'Pull day', duration_minutes: 62 },
  { date: dayOffset(-6), type: 'run', description: 'Schenley loop', duration_minutes: 41 },
  { date: dayOffset(-7), type: 'sport', description: 'pickup basketball', duration_minutes: 90 },
  { date: dayOffset(-10), type: 'lift', description: 'Legs', duration_minutes: 58 },
]

write(
  'data/workouts.json',
  WORKOUTS.map((entry, index) => ({ id: id('w'), source: 'app', created_at: ts(index), ...entry }))
)

console.log(root)
